language: python
cache:
  directories:
    - $HOME/miniconda3

before_cache:
  - rm -rf $HOME/miniconda3/pkgs/cache
  - rm -rf $HOME/miniconda3/envs/hosts
  - rm -rf $HOME/miniconda3/conda-meta/history
  - touch $HOME/miniconda3/conda-meta/history

os:
  - linux
env:
  - PYTHON_VERSION="3.5"
  - PYTHON_VERSION="3.6"
  - PYTHON_VERSION="3.7"
  - PYTHON_VERSION="2.7"

before_install:
  - export PATH="$HOME/miniconda3/bin:$PATH"

branches:
  only:
  - master
  - /^v.*$/
install: 
- ci/install_conda.sh
- ci/setup_conda_env.sh
- pip install .
# # command to run tests, e.g. python setup.py test
script:  
  - python --version
  - wget http://tide.dfci.harvard.edu/download/GSE78220.self_subtract.zip
  - tidepy GSE78220.self_subtract.zip -c Melanoma -o test 
after_sucess:
 
