language: python
cache:
  directories:
    - $HOME/miniconda3

before_cache:
  - rm -rf $HOME/miniconda3/pkgs/cache
  - rm -rf $HOME/miniconda3/envs/hosts
  - rm -rf $HOME/miniconda3/conda-meta/history
  - touch $HOME/miniconda3/conda-meta/history

os:
  - linux
  - osx

env:
  - PYTHON_VERSION="3.5"
  - PYTHON_VERSION="3.6"
  - PYTHON_VERSION="3.7"

before_install:
  - export PATH="$HOME/miniconda3/bin:$PATH"

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"
branches:
  only:
  - master
  - /^v.*$/
install: 
- ci/install_conda.sh
- ci/setup_conda_env.sh
- pip install .
# # command to run tests, e.g. python setup.py test
script:  
  - tidepy GSE78220.self_subtract.zip -c Melanoma -o test 
after_sucess:
 
