language: python
python:
 - 2.7
 - 3.3
 - 3.5
 - 3.8

os:
  - linux

branches:
  only:
  - master
  - /^v.*$/
install: 
- pip install .
# # command to run tests, e.g. python setup.py test
script:  
  - python --version
  - wget http://tide.dfci.harvard.edu/download/GSE78220.self_subtract.zip
  - tidepy GSE78220.self_subtract.zip -c Melanoma -o test 
after_sucess:
 
